# Generated by Django 3.2.7 on 2023-02-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=255)),
                ('cover_image', models.URLField()),
                ('cover_text', models.TextField()),
                ('cover_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('text', models.TextField()),
                ('pos', models.PositiveSmallIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('web_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.webstory')),
            ],
        ),
    ]
