# Generated by Django 3.2.7 on 2023-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20230203_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='cover_image',
            field=models.FileField(upload_to='static/cover'),
        ),
    ]
