# Generated by Django 3.2.7 on 2023-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20230203_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstory',
            name='cover_url',
            field=models.URLField(default=True),
        ),
    ]
