# Generated by Django 3.2.7 on 2023-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_webstory_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
