# Generated by Django 3.2.7 on 2023-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_webstory_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstory',
            name='cover_extension',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
