# Generated by Django 3.2.7 on 2023-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_webstory_cover_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
