# Generated by Django 3.2.7 on 2023-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20230203_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='webstory',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
