# Generated by Django 3.2.7 on 2023-02-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20230203_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='permalink',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
