# Generated by Django 3.2.7 on 2023-02-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_alter_webstory_permalink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='webstory',
            name='cover_extension',
        ),
        migrations.RemoveField(
            model_name='webstory',
            name='cover_image',
        ),
    ]
